### ISSUE TITLE
Add detection of preferred color schemes

### ISSUE THREAD

**Issue by wcoder** [wcoder/wcoder.github.io#4]
> New standard is registered on [W3C in Media Queries Level 5](https://drafts.csswg.org/mediaqueries-5/#prefers-color-scheme).

Example:
```css
/* Light mode */
@media (prefers-color-scheme: light) {
    body {
        background-color: #000;
        color: white;
    }
}

/* Dark mode */
@media (prefers-color-scheme: dark) {
    body {
        background-color: #000;
        color: white;
    }
}
```
