### ISSUE TITLE
Support un/printable UI

### ISSUE THREAD

**Issue by wcoder** [wcoder/wcoder.github.io#9]
```scss
%unprintable {
  @media print {
    display: none !important;
    visibility: hidden;
  }
}

.unprintable { @extend %unprintable; }

%printable {
  @media not print  {
    display: none !important;
    visibility: hidden;
  }
}

.printable { @extend %printable; }


.header {
  @extend %desktop-only;
  @extend %unprintable;
 // ....
}
```
